name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
          - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/adk-form-processor
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy adk-form-processor \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/adk-form-processor \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},MONGODB_URI=${{ secrets.MONGODB_URI }},DATABASE_NAME=${{ secrets.DATABASE_NAME }},USE_PROVIDER=${{ secrets.USE_PROVIDER }},DEFAULT_OCR_LANG=${{ secrets.DEFAULT_OCR_LANG }},LOG_LEVEL=${{ secrets.LOG_LEVEL }}" \
          --memory 1Gi \
          --timeout 300s
          
    - name: Display service URL
      run: |
        echo "Service deployed to: $(gcloud run services describe adk-form-processor --platform managed --region us-central1 --format 'value(status.url)')"
